services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
     - db  
  db:
    image: postgis/postgis
    volumes:
#      - ./db_backup/read:/docker-entrypoint-initdb.d/:ro
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - ./app/staticfiles:/home/app/web/staticfiles
#      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app      
  admin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    ports:
      - "8080:80"
volumes:
  postgres_data:
  pgadmin-data: