# Generated by Django 5.2.4 on 2025-08-03 12:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_kurz', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='frontend.dataset')),
            ],
            options={
                'verbose_name_plural': 'Data Geometries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usage_code1', models.IntegerField()),
                ('usage_code2', models.IntegerField()),
                ('usage_code3', models.IntegerField()),
                ('cat_inno', models.IntegerField()),
                ('cat_wert', models.IntegerField()),
                ('cat_fili', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='frontend.datageometry')),
            ],
            options={
                'verbose_name_plural': 'Data Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
