# Generated by Django 5.2.5 on 2025-10-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_typology_dataset_typology_typologyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_code1_label', models.CharField(default='Usage Code 1', max_length=100)),
                ('usage_code1_enabled', models.BooleanField(default=True)),
                ('usage_code2_label', models.CharField(default='Usage Code 2', max_length=100)),
                ('usage_code2_enabled', models.BooleanField(default=True)),
                ('usage_code3_label', models.CharField(default='Usage Code 3', max_length=100)),
                ('usage_code3_enabled', models.BooleanField(default=True)),
                ('cat_inno_label', models.CharField(default='Category Innovation', max_length=100)),
                ('cat_inno_enabled', models.BooleanField(default=True)),
                ('cat_wert_label', models.CharField(default='Category Value', max_length=100)),
                ('cat_wert_enabled', models.BooleanField(default=True)),
                ('cat_fili_label', models.CharField(default='Category Filial', max_length=100)),
                ('cat_fili_enabled', models.BooleanField(default=True)),
                ('year_label', models.CharField(default='Year', max_length=100)),
                ('year_enabled', models.BooleanField(default=True)),
                ('name_label', models.CharField(default='Entry Name', max_length=100)),
                ('name_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_config', to='frontend.dataset')),
            ],
            options={
                'verbose_name': 'Dataset Field Configuration',
                'verbose_name_plural': 'Dataset Field Configurations',
            },
        ),
    ]
