# Generated by Django 5.2.5 on 2025-10-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_datasetfieldconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name (will be used as column name)', max_length=100)),
                ('label', models.CharField(help_text='Display label for the field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('choice', 'Choice')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, help_text='Help text to display to users', null=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for choice fields', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='frontend.dataset')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'ordering': ['order', 'name'],
                'unique_together': {('dataset', 'name')},
            },
        ),
    ]
