# Generated by Django 5.2.7 on 2025-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field values for this entry'),
        ),
    ]
