# Generated by Django 5.2.7 on 2025-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_add_custom_fields_to_dataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_standard_field',
            field=models.BooleanField(default=False, help_text='Whether this is a standard field (name, usage_code1, etc.)'),
        ),
    ]
